# Generated by Django 4.2.7 on 2025-09-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponses',
            fields=[
                ('responseid', models.IntegerField(db_column='ResponseId', primary_key=True, serialize=False)),
                ('vendorid', models.IntegerField(blank=True, db_column='VendorId', null=True)),
                ('responses', models.JSONField(blank=True, db_column='Responses', null=True)),
                ('submittedat', models.DateTimeField(blank=True, db_column='SubmittedAt', null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'db_table': 'questionnaire_responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorQuestionnaireAssignments',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=11, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Vendor Questionnaire Assignment',
                'verbose_name_plural': 'Vendor Questionnaire Assignments',
                'db_table': 'vendor_questionnaire_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('questionnaire_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('questionnaire_name', models.CharField(max_length=255)),
                ('questionnaire_type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ANNUAL', 'Annual'), ('INCIDENT', 'Incident'), ('CUSTOM', 'Custom')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor_category_id', models.BigIntegerField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=8)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'db_table': 'questionnaires',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('CHECKBOX', 'Checkbox'), ('RATING', 'Rating'), ('FILE_UPLOAD', 'File Upload'), ('DATE', 'Date'), ('NUMBER', 'Number')], max_length=15)),
                ('question_category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField()),
                ('scoring_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('options', models.JSONField(blank=True, null=True)),
                ('conditional_logic', models.JSONField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vendor_questionnaire.questionnaires')),
            ],
            options={
                'verbose_name': 'Questionnaire Question',
                'verbose_name_plural': 'Questionnaire Questions',
                'db_table': 'questionnaire_questions',
                'ordering': ['display_order'],
                'managed': True,
            },
        ),
    ]
