# Generated by Django 4.2.7 on 2025-09-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_core', '__first__'),
        ('vendor_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireAssignments',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='ASSIGNED', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendor_core.users')),
            ],
            options={
                'verbose_name': 'Questionnaire Assignment',
                'verbose_name_plural': 'Questionnaire Assignments',
                'db_table': 'questionnaire_assignments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponseSubmissions',
            fields=[
                ('response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_response', models.TextField(blank=True, null=True)),
                ('vendor_comment', models.TextField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('file_uploads', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_questionnaire.questionnaireassignments')),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'db_table': 'questionnaire_response_submissions',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='VendorQuestionnaireAssignments',
        ),
        migrations.AlterModelOptions(
            name='questionnairequestions',
            options={'managed': False, 'ordering': ['display_order'], 'verbose_name': 'Questionnaire Question', 'verbose_name_plural': 'Questionnaire Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionnaires',
            options={'managed': False, 'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
        migrations.AddField(
            model_name='questionnaireresponsesubmissions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_responses', to='vendor_questionnaire.questionnairequestions'),
        ),
        migrations.AddField(
            model_name='questionnaireassignments',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vendor_questionnaire.questionnaires'),
        ),
        migrations.AddField(
            model_name='questionnaireassignments',
            name='temp_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_assignments', to='vendor_core.tempvendor'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireresponsesubmissions',
            unique_together={('assignment', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireassignments',
            unique_together={('temp_vendor', 'questionnaire')},
        ),
    ]
