"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import pymysql
import os
import sys
import warnings
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# =========================================================================
# SUPPRESS WARNINGS - Clean up terminal output
# =========================================================================
# Suppress Google API Python version warning
warnings.filterwarnings("ignore", category=FutureWarning, module="google.api_core")
# Suppress model registration warnings (we're using database router)
warnings.filterwarnings("ignore", category=RuntimeWarning, message=".*already registered.*")
# Suppress ALL development server warnings
warnings.filterwarnings("ignore", module="django.core.management.commands.runserver")
warnings.filterwarnings("ignore", message=".*development server.*")
warnings.filterwarnings("ignore", message=".*production.*")
import logging
logging.getLogger('django.utils.autoreload').setLevel(logging.ERROR)
logging.getLogger('django.server').setLevel(logging.ERROR)  # Suppress server startup messages

# Configure PyMySQL to be used as the MySQL driver
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add ai_services to Python path
sys.path.append(str(BASE_DIR.parent))

"""
SECURITY NOTE:
- DO NOT hardcode any secrets, API keys, passwords, or tokens in this file.
- All sensitive values must come from environment variables (or a .env file that is NOT committed).
"""

# External service keys (load from environment / .env)
PERPLEXITY_API_KEY = os.environ.get("PERPLEXITY_API_KEY", "")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be provided via environment variable in production.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "changeme-in-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'riskavaire.vardaands.com',  # Main production domain
    'grc-tprm.vardaands.com',
    'grc-backend.vardaands.com',
    '15.207.108.158',
    '13.204.228.21',
    'e581-2405-201-c00b-4973-29e6-34b2-9eae-1e0c.ngrok-free.app',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "grc",
    
    # =========================================================================
    # TPRM INTEGRATION - Third Party Risk Management Apps
    # =========================================================================
    # Third-party dependencies for TPRM
    "django_filters",
    "drf_yasg",
    "import_export",
    "simple_history",
    
    # TPRM Core Apps
    "tprm_backend.core",
    "tprm_backend.slas",
    "tprm_backend.audits",
    "tprm_backend.notifications",
    "tprm_backend.quick_access",
    "tprm_backend.compliance",
    "tprm_backend.bcpdrp",
    "tprm_backend.risk_analysis",
    "tprm_backend.contract_risk_analysis",
    "tprm_backend.mfa_auth",
    "tprm_backend.rbac",
    "tprm_backend.admin_access",
    "tprm_backend.consent",
    "tprm_backend.contracts",
    "tprm_backend.audits_contract",
    "tprm_backend.rfp",
    "tprm_backend.rfp_approval",
    "tprm_backend.rfp_risk_analysis",
    "tprm_backend.ocr_app",
    "tprm_backend.global_search",
    "tprm_backend.risk_analysis_vendor",
    
    # TPRM Vendor Apps
    "tprm_backend.apps.vendor_core",
    "tprm_backend.apps.vendor_auth",
    "tprm_backend.apps.vendor_risk",
    "tprm_backend.apps.vendor_questionnaire",
    "tprm_backend.apps.vendor_dashboard",
    "tprm_backend.apps.vendor_lifecycle",
    "tprm_backend.apps.vendor_approval",
]

MIDDLEWARE = [
    "grc.middleware.RequestLoggingMiddleware",  # ADDED: Log all requests FIRST
    "corsheaders.middleware.CorsMiddleware",
    # "grc.middleware.CORSMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "grc.middleware.SessionTimeoutMiddleware",  # TEMPORARILY DISABLED: Causing immediate logout issues
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Enterprise Security Headers Middleware - Adds comprehensive security headers to all responses
    "grc.middleware.EnterpriseSecurityHeadersMiddleware",
    "grc.middleware.JWTAuthenticationMiddleware",
    # MULTI-TENANCY: Add tenant context middleware (after JWT authentication)
    "grc.tenant_middleware.TenantContextMiddleware",
    "grc.tenant_middleware.TenantIsolationMiddleware",
    # MULTI-TENANCY: Add TPRM tenant context middleware for TPRM modules
    "tprm_backend.core.tenant_middleware.TenantContextMiddleware",
    "tprm_backend.core.tenant_middleware.TenantIsolationMiddleware",
    "grc.middleware.AuditLoggingMiddleware",
    # AUTO-DECRYPT: Automatically decrypt any encrypted data in API responses (safety net)
    "grc.utils.auto_decrypt_middleware.AutoDecryptMiddleware",
    # Removed grc.rbac.middleware.GRCRBACMiddleware - using simplified decorator-based RBAC instead
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR.parent / "frontend" / "dist",  # Vue.js production build
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

        # "USER": "admin",
        # "PASSWORD": "Vardaan123",
        # "HOST": "mydb.c1womgmu83di.ap-south-1.rds.amazonaws.com",


DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": os.environ.get("DB_NAME", "grc2"),
        "USER": os.environ.get("DB_USER", "changeme"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "changeme"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+00:00'",
            "charset": "utf8mb4",
            "connect_timeout": 10,
        },
        "CONN_MAX_AGE": 60,  # Reuse connections for 60 seconds
        "CONN_HEALTH_CHECKS": True,  # Check connection health before use
    },
    # =========================================================================
    # TPRM Database - Third Party Risk Management
    # =========================================================================
    "tprm": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": os.environ.get("TPRM_DB_NAME", "tprm_integration"),
        "USER": os.environ.get("TPRM_DB_USER", os.environ.get("DB_USER", "admin")),
        "PASSWORD": os.environ.get("TPRM_DB_PASSWORD", os.environ.get("DB_PASSWORD", "rootroot")),
        "HOST": os.environ.get("TPRM_DB_HOST", "tprmintegration.c1womgmu83di.ap-south-1.rds.amazonaws.com"),
        "PORT": os.environ.get("TPRM_DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
            "connect_timeout": 10,
        },
        "CONN_MAX_AGE": 60,  # Reuse connections for 60 seconds
        "CONN_HEALTH_CHECKS": True,  # Check connection health before use
    }
}

# =========================================================================
# DATABASE ROUTER - Route TPRM apps to TPRM database
# =========================================================================
DATABASE_ROUTERS = ['backend.tprm_router.TPRMDatabaseRouter']

# TPRM apps that should use the tprm database
TPRM_APPS = [
    'tprm_backend.core',
    'tprm_backend.slas',
    'tprm_backend.audits',
    'tprm_backend.notifications',
    'tprm_backend.quick_access',
    'tprm_backend.compliance',
    'tprm_backend.bcpdrp',
    'tprm_backend.risk_analysis',
    'tprm_backend.contract_risk_analysis',
    'tprm_backend.mfa_auth',
    'tprm_backend.rbac',
    'tprm_backend.admin_access',
    'tprm_backend.consent',  # TPRM Consent Management
    'tprm_backend.contracts',
    'tprm_backend.audits_contract',
    'tprm_backend.rfp',
    'tprm_backend.rfp_approval',
    'tprm_backend.rfp_risk_analysis',
    'tprm_backend.ocr_app',
    'tprm_backend.global_search',
    'tprm_backend.risk_analysis_vendor',
    'tprm_backend.apps.vendor_core',
    'tprm_backend.apps.vendor_auth',
    'tprm_backend.apps.vendor_risk',
    'tprm_backend.apps.vendor_questionnaire',
    'tprm_backend.apps.vendor_dashboard',
    'tprm_backend.apps.vendor_lifecycle',
    'tprm_backend.apps.vendor_approval',
]

# ===== SESSION CONFIGURATION - CRITICAL FOR AUTHENTICATION! =====
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database sessions
SESSION_SAVE_EVERY_REQUEST = False  # Don't extend session on every request - allows timeout to work properly
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour (3600 seconds) of inactivity
SESSION_COOKIE_NAME = 'grc_sessionid'  # Custom session cookie name
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access (needed for SPA)
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS (False for HTTP/development)
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests with same-site protection (will be overridden by middleware for OAuth)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after browser close
SESSION_COOKIE_DOMAIN = None  # Use default domain
SESSION_COOKIE_PATH = '/'  # Session cookie available for entire site

# Add RBAC configuration for simplified decorator-based approach
RBAC_CONFIG = {
    'ENABLE_RBAC': False,  # Temporarily disable RBAC to fix 403 errors
    'LOG_PERMISSIONS': True,  # Log permission checks for debugging
    'DEBUG_MODE': True,  # Enable detailed debug logging during development
}

# RBAC Decorator Bypass for development
RBAC_DECORATOR_BYPASS = True  # Bypass RBAC decorators temporarily to fix 403 errors

# Add logging configuration for debugging
# IMPORTANT: Don't override django.server logger - it handles request logging automatically
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # CRITICAL: Keep Django's default loggers
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # DON'T override django.server or django.request - Django handles request logging automatically
        # Only suppress verbose autoreload messages
        'django.utils.autoreload': {
            'handlers': [],
            'level': 'ERROR',
            'propagate': False,
        },
        # GRC app logging
        'grc': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'grc.rbac': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # TPRM app logging
        'tprm_backend': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
    # Root logger - catches everything else
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic command

# Additional locations for static files (includes Vue.js dist)
# Only add directories that actually exist to avoid warnings
_potential_static_dirs = [
    BASE_DIR.parent / 'frontend' / 'dist' / 'assets',  # Vue.js compiled assets
    BASE_DIR.parent / 'frontend' / 'dist' / 'css',     # Vue.js CSS
    BASE_DIR.parent / 'frontend' / 'dist' / 'js',      # Vue.js JS
]
STATICFILES_DIRS = [d for d in _potential_static_dirs if d.exists()]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'MEDIA_ROOT'
TEMP_MEDIA_ROOT = BASE_DIR / 'TEMP_MEDIA_ROOT'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================================
# SILENCED SYSTEM CHECKS - Suppress expected warnings
# =========================================================================
# Silence models.W035 warnings for tables shared across GRC and TPRM
# These are expected since we use DATABASE_ROUTERS to route to separate DBs
SILENCED_SYSTEM_CHECKS = [
    "models.W035",  # db_table used by multiple models (expected with multi-DB)
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://grc-tprm.vardaands.com",
    "http://localhost:3000",  # TPRM frontend development server
    "http://localhost:8081",  # Vue.js development server
    "http://localhost:8080",  # Alternative Vue.js port
    "http://127.0.0.1:3000",  # TPRM frontend development server (127.0.0.1)
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://15.207.108.158:8080",  # AWS deployment frontend (HTTP)
    "http://15.207.108.158:8081",  # AWS deployment frontend alternative (HTTP)
    "https://15.207.108.158:8000",  # AWS backend HTTPS
    "https://15.207.108.158:8080",  # AWS frontend HTTPS
    "https://15.207.108.158:8081",  # AWS frontend alternative HTTPS
    "http://13.201.54.231",  # Deployed frontend URL
    "https://13.201.54.231",  # Deployed frontend URL (HTTPS)
    "http://13.201.54.231:80",  # Deployed frontend URL with port
    "http://13.201.54.231:8080",  # Deployed frontend URL with port
    "http://13.201.54.231:8081",  # Deployed frontend URL with port
    "https://grc-backend.vardaands.com",  # New server IP with port
    "https://13.204.228.21:8000",  # New server IP with port (HTTPS)
    "http://13.204.228.21:8000",
    "https://riskavaire.vardaands.com",
]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "https://riskavaire.vardaands.com",
    "http://localhost:3000",  # TPRM frontend development server
    "http://localhost:8081",  # Vue.js development server
    "http://localhost:8080",  # Alternative Vue.js port
    "http://127.0.0.1:3000",  # TPRM frontend development server (127.0.0.1)
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://15.207.108.158:8080",  # AWS deployment frontend (HTTP)
    "http://15.207.108.158:8081",  # AWS deployment frontend alternative (HTTP)
    "https://15.207.108.158:8000",  # AWS backend HTTPS
    "https://15.207.108.158:8080",  # AWS frontend HTTPS
    "https://15.207.108.158:8081",  # AWS frontend alternative HTTPS
    "http://13.201.54.231",  # Deployed frontend URL
    "https://13.201.54.231",  # Deployed frontend URL (HTTPS)
    "http://13.201.54.231:80",  # Deployed frontend URL with port
    "http://13.201.54.231:8080",  # Deployed frontend URL with port
    "http://13.201.54.231:8081",  # Deployed frontend URL with port
    "https://grc-backend.vardaands.com",  # New server IP with port
    "https://13.204.228.21:8000",  # New server IP with port (HTTPS)
    "http://13.204.228.21:8000",
    "https://grc-tprm.vardaands.com",
]

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookie',  # CRITICAL: Allow cookie header for session authentication
    'set-cookie',  # Allow set-cookie header responses
]

# HTTPS Security Settings
# Note: Set these to True when using valid SSL certificates in production
# For self-signed certificates in development, keep them as False
CSRF_COOKIE_SECURE = False  # Set to True with valid SSL certificates (False for HTTP/development)
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token

# Session settings for HTTPS (duplicate - remove if causing issues)
# SESSION_COOKIE_SECURE = False  # Set to True with valid SSL certificates
# SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access to session cookies
# SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
# SESSION_COOKIE_DOMAIN = None  # Allow all domains in development

# Additional HTTPS security headers (enable in production)
SECURE_SSL_REDIRECT = False  # Set to True to redirect all HTTP to HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For reverse proxy
SECURE_HSTS_SECONDS = 0  # Set to 31536000 (1 year) in production with HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Set to True in production
SECURE_HSTS_PRELOAD = False  # Set to True in production

# JWT Settings
JWT_SECRET_KEY = SECRET_KEY
JWT_ACCESS_TOKEN_LIFETIME = 3600  # 1 hour in seconds
JWT_REFRESH_TOKEN_LIFETIME = 604800  # 7 days in seconds
# reCAPTCHA Configuration
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # Default is Google's test key
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # Default is Google's test key
RECAPTCHA_ENABLED = os.environ.get('RECAPTCHA_ENABLED', 'true').lower() == 'true'
# SimpleJWT configuration with refresh token rotation & blacklist
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=JWT_ACCESS_TOKEN_LIFETIME),
    "REFRESH_TOKEN_LIFETIME": timedelta(seconds=JWT_REFRESH_TOKEN_LIFETIME),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # Add token auth as fallback
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Temporarily allow all for testing
    ],
    # Increase throttling and timeout settings
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '500/day',
    },
    # Allow larger request size
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
# Increase Django's data upload limit for large exports
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB (increased from 10MB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Maximum file upload size (for file uploads)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB (increased from 10MB)
# S3 Microservice settings
S3_MICROSERVICE_URL = 'http://localhost:3000'  # Default URL for S3 microservice

# Report generation settings
REPORTS_DIR = Path(BASE_DIR) / 'Reports'
REPORTS_DIR.mkdir(exist_ok=True)  # Create Reports directory if it doesn't exist

# OpenAI API Configuration
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

# Grok / xAI or other LLM provider
GROK_API_KEY = os.environ.get("GROK_API_KEY", "")
GROK_MODEL = os.environ.get("GROK_MODEL", "llama-3.1-8b-instant")



# Licensing toggle: allow disabling external license checks temporarily
LICENSE_CHECK_ENABLED = os.environ.get('LICENSE_CHECK_ENABLED', 'true').lower() == 'true'
# Increase Django's data upload limit for large exports
 
LICENSE_CHECK_ENABLED = False
 
# Ollama configuration
# Ollama configuration
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://13.126.18.17:11434')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/2')
# Default timeout (seconds) for Ollama HTTP requests
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '600'))
# Default Ollama model to use (must exist on server per /api/tags)
# Recommended: Use quantized models for better performance (e.g., llama3.2:3b-instruct-q4_K_M)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:3b-instruct-q4_K_M')

# Risk AI Provider Selection
# Set to 'openai' or 'ollama' to choose which AI provider to use for risk document processing
# Default: 'ollama' if both are configured, else 'openai'
RISK_AI_PROVIDER = os.environ.get('RISK_AI_PROVIDER', 'ollama')

# ===== PASSWORD EXPIRY CONFIGURATION =====
# Password expiry in days (90 days)
PASSWORD_EXPIRY_DAYS = int(os.environ.get('PASSWORD_EXPIRY_DAYS', '90'))
# Days before expiry to send warning email (7 days before expiry)
PASSWORD_EXPIRY_WARNING_DAYS = int(os.environ.get('PASSWORD_EXPIRY_WARNING_DAYS', '7'))
# Number of previous passwords to check for reuse prevention (5 passwords)
PASSWORD_HISTORY_COUNT = int(os.environ.get('PASSWORD_HISTORY_COUNT', '5'))

# =========================================================================
# USER INACTIVITY SETTINGS
# =========================================================================
# Number of days of inactivity before a user is automatically deactivated
# Users who haven't logged in for this many days will have their IsActive status changed to 'N'
# Default: 90 days (3 months)
USER_INACTIVITY_DAYS = int(os.environ.get('USER_INACTIVITY_DAYS', '90'))
# Whether to send email notifications to users before deactivation (future feature)
USER_INACTIVITY_EMAIL_ENABLED = os.environ.get('USER_INACTIVITY_EMAIL_ENABLED', 'false').lower() == 'true'
# Days before deactivation to send warning email (future feature)
USER_INACTIVITY_WARNING_DAYS = int(os.environ.get('USER_INACTIVITY_WARNING_DAYS', '7'))

# ===== EMAIL AND NOTIFICATION CONFIGURATION =====

# SMTP Configuration for Email
SMTP_SERVER = os.environ.get('SMTP_SERVER', 'smtp.gmail.com')
SMTP_PORT = int(os.environ.get('SMTP_PORT', '587'))
SMTP_EMAIL = os.environ.get('SMTP_EMAIL', '')
SMTP_PASSWORD = os.environ.get('SMTP_PASSWORD', '')

# Gmail Configuration
GMAIL_USER = os.environ.get('GMAIL_USER', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

# Email Configuration
# For Azure AD: Use the Azure AD registered email (praharshitha.d@vardaanglobal.com)
# IMPORTANT: For Azure Graph API, DEFAULT_FROM_EMAIL must be an Azure AD registered email (e.g., @vardaanglobal.com)
# The AzureADEmailBackend will automatically use 'praharshitha.d@vardaanglobal.com' if a Gmail or non-Azure email is configured
# Priority: Environment variable > Azure AD default
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'praharshitha.d@vardaanglobal.com')
# Ensure we never use a Gmail address for Azure AD emails
if '@gmail.com' in DEFAULT_FROM_EMAIL.lower():
    DEFAULT_FROM_EMAIL = 'praharshitha.d@vardaanglobal.com'
    print(f"[SETTINGS] DEFAULT_FROM_EMAIL was Gmail, changed to Azure AD email: {DEFAULT_FROM_EMAIL}")
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME', 'GRC System')

# Django Email Backend Configuration
EMAIL_BACKEND = 'grc.routes.Global.azure_email_backend.AzureADEmailBackend'
EMAIL_HOST = SMTP_SERVER
EMAIL_PORT = SMTP_PORT
EMAIL_USE_TLS = True
EMAIL_HOST_USER = SMTP_EMAIL
EMAIL_HOST_PASSWORD = SMTP_PASSWORD


# Azure AD Email Configuration
# Note: Environment variables take precedence. Defaults provided for immediate use.
AZURE_AD_TENANT_ID = os.environ.get('AZURE_AD_TENANT_ID', 'aa7c8c45-41a3-4453-bc9a-3adfe8ff5fb6')
AZURE_AD_CLIENT_ID = os.environ.get('AZURE_AD_CLIENT_ID', '127107b0-7144-4246-b2f4-160263ceb3c9')
AZURE_AD_CLIENT_SECRET = os.environ.get('AZURE_AD_CLIENT_SECRET', 'sVr8Q~3b0OS~L5NFIaWGomhiGwSwFuNMnW7RPamR')
AZURE_AD_SCOPE = os.environ.get('AZURE_AD_SCOPE', 'https://graph.microsoft.com/.default')
# WhatsApp API Configuration
WHATSAPP_API_URL = os.environ.get('WHATSAPP_API_URL', 'https://graph.facebook.com/v21.0/521803094347148/messages')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_SENDER_PHONE = os.environ.get('WHATSAPP_SENDER_PHONE', '')
TEMPLATE_NAME = os.environ.get('WHATSAPP_TEMPLATE_NAME', 'hello_world')

# AWS S3 Configuration
AWS_BUCKET_NAME = os.environ.get("AWS_BUCKET_NAME", "")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_REGION = os.environ.get("AWS_REGION", "ap-south-1")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "ap-south-1")
# Toggle between local and deployed environments (define early as it's used in other configs)
USE_LOCAL_DEVELOPMENT = os.environ.get('USE_LOCAL_DEVELOPMENT', 'true').lower() == 'true'  # Set to False for production

# Helper function to clean environment variable values (remove quotes)
# Define early so it can be used in OAuth configurations
def clean_env_value(value, default=''):
    """Remove quotes from environment variable values"""
    if not value:
        return default
    value = str(value).strip()
    # Remove quotes from start and end
    while (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    return value.strip("'\"")
# Microsoft Azure AD Configuration for Sentinel Integration
MICROSOFT_CLIENT_ID = os.environ.get("MICROSOFT_CLIENT_ID", "")
MICROSOFT_TENANT_ID = os.environ.get("MICROSOFT_TENANT_ID", "")
MICROSOFT_CLIENT_SECRET = os.environ.get("MICROSOFT_CLIENT_SECRET", "")
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'MICROSOFT_REDIRECT_URI' in os.environ:
    REDIRECT_URI = clean_env_value(os.environ.get('MICROSOFT_REDIRECT_URI'))
else:
    REDIRECT_URI = (
        'http://localhost:8000/auth/sentinel/callback' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/auth/sentinel/callback'
    )
MICROSOFT_AUTHORITY = os.environ.get("MICROSOFT_AUTHORITY", "https://login.microsoftonline.com/common")
MICROSOFT_USER = os.environ.get("MICROSOFT_USER", "")

# Azure Sentinel Configuration
AZURE_SUBSCRIPTION_ID = os.environ.get("AZURE_SUBSCRIPTION_ID", "")
AZURE_RESOURCE_GROUP = os.environ.get("AZURE_RESOURCE_GROUP", "")
AZURE_WORKSPACE_NAME = os.environ.get("AZURE_WORKSPACE_NAME", "")

# Jira OAuth Configuration

JIRA_CLIENT_ID = clean_env_value(os.environ.get("JIRA_CLIENT_ID", ""))
JIRA_CLIENT_SECRET = clean_env_value(os.environ.get("JIRA_CLIENT_SECRET", ""))
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'JIRA_REDIRECT_URI' in os.environ:
    JIRA_REDIRECT_URI = clean_env_value(os.environ.get('JIRA_REDIRECT_URI'))
else:
    JIRA_REDIRECT_URI = (
        'http://127.0.0.1:8000/api/jira/oauth-callback/' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/api/jira/oauth-callback'  # No trailing slash to match Atlassian registration
    )
JIRA_SCOPES = clean_env_value(os.environ.get("JIRA_SCOPES", 'read:jira-user read:jira-work'), 'read:jira-user read:jira-work')

# Database convenience env vars (for raw connections / other services)
DB_HOST = os.environ.get('DB_HOST', '')
DB_USER = os.environ.get('DB_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_NAME = os.environ.get('DB_NAME', '')

BAMBOOHR_CLIENT_ID = clean_env_value(os.environ.get("BAMBOOHR_CLIENT_ID", ""))
BAMBOOHR_CLIENT_SECRET = clean_env_value(os.environ.get("BAMBOOHR_CLIENT_SECRET", ""))
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8080' if USE_LOCAL_DEVELOPMENT else 'http://example.com')
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'BAMBOOHR_REDIRECT_URI' in os.environ:
    BAMBOOHR_REDIRECT_URI = clean_env_value(os.environ.get('BAMBOOHR_REDIRECT_URI'))
else:
    BAMBOOHR_REDIRECT_URI = (
        'http://127.0.0.1:8000/api/bamboohr/oauth-callback/' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/api/bamboohr/oauth-callback/'
    )
 
BAMBOOHR_FLASK_SERVER_URL = os.environ.get(
    'BAMBOOHR_FLASK_SERVER_URL',
    'http://127.0.0.1:5000' if USE_LOCAL_DEVELOPMENT else 'https://grc-backend.vardaands.com'
)

BAMBOOHR_SCOPES = clean_env_value(
    os.environ.get('BAMBOOHR_SCOPES', 'email openid employee company:info employee:contact employee:job employee:name employee:photo employee_directory'),
    'email openid employee company:info employee:contact employee:job employee:name employee:photo employee_directory'
)
 
# Google OAuth Configuration for SSO
GOOGLE_CLIENT_ID = clean_env_value(os.environ.get("GOOGLE_CLIENT_ID", ""))
GOOGLE_CLIENT_SECRET = clean_env_value(os.environ.get("GOOGLE_CLIENT_SECRET", ""))
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'GOOGLE_REDIRECT_URI' in os.environ:
    GOOGLE_REDIRECT_URI = clean_env_value(os.environ.get('GOOGLE_REDIRECT_URI'))
else:
    GOOGLE_REDIRECT_URI = (
        'http://localhost:8000/api/google/oauth-callback/' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/api/google/oauth-callback/'
    )
GOOGLE_SCOPES = clean_env_value(
    os.environ.get('GOOGLE_SCOPES', 'openid email profile'),
    'openid email profile'
)
 
 
 
 

 
# OAuth State Verification (set to 'true' to skip in development)
# WARNING: Only use this in local development! Always verify state in production
SKIP_OAUTH_STATE_VERIFICATION = os.environ.get('SKIP_OAUTH_STATE_VERIFICATION', 'true' if DEBUG else 'false')

# MFA Configuration
# Set MFA_ENABLED=true to enable Multi-Factor Authentication, false to disable
MFA_ENABLED = os.environ.get('MFA_ENABLED', 'true').lower() == 'true'
 


# Set environment variables so they can be accessed via os.getenv() by notification_service.py
os.environ.setdefault('DB_HOST', DB_HOST)
os.environ.setdefault('DB_USER', DB_USER)
os.environ.setdefault('DB_PASSWORD', DB_PASSWORD)
os.environ.setdefault('DB_NAME', DB_NAME)

os.environ.setdefault('SMTP_SERVER', SMTP_SERVER)
os.environ.setdefault('SMTP_PORT', str(SMTP_PORT))
os.environ.setdefault('SMTP_EMAIL', SMTP_EMAIL)
os.environ.setdefault('SMTP_PASSWORD', SMTP_PASSWORD)

os.environ.setdefault('GMAIL_USER', GMAIL_USER)
os.environ.setdefault('GMAIL_APP_PASSWORD', GMAIL_APP_PASSWORD)

os.environ.setdefault('DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL)
os.environ.setdefault('DEFAULT_FROM_NAME', DEFAULT_FROM_NAME)

os.environ.setdefault('WHATSAPP_PHONE_NUMBER_ID', WHATSAPP_PHONE_NUMBER_ID)
os.environ.setdefault('WHATSAPP_ACCESS_TOKEN', WHATSAPP_ACCESS_TOKEN)
os.environ.setdefault('WHATSAPP_SENDER_PHONE', WHATSAPP_SENDER_PHONE)

os.environ.setdefault('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
os.environ.setdefault('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)
os.environ.setdefault('AWS_STORAGE_BUCKET_NAME', AWS_STORAGE_BUCKET_NAME)
os.environ.setdefault('AWS_S3_REGION_NAME', AWS_S3_REGION_NAME)

os.environ.setdefault('MICROSOFT_CLIENT_ID', MICROSOFT_CLIENT_ID)
os.environ.setdefault('MICROSOFT_CLIENT_SECRET', MICROSOFT_CLIENT_SECRET)
os.environ.setdefault('MICROSOFT_TENANT_ID', MICROSOFT_TENANT_ID)
os.environ.setdefault('MICROSOFT_AUTHORITY', MICROSOFT_AUTHORITY)
os.environ.setdefault('MICROSOFT_USER', MICROSOFT_USER)

os.environ.setdefault('JIRA_CLIENT_ID', JIRA_CLIENT_ID)
os.environ.setdefault('JIRA_CLIENT_SECRET', JIRA_CLIENT_SECRET)
os.environ.setdefault('JIRA_REDIRECT_URI', JIRA_REDIRECT_URI)
os.environ.setdefault('JIRA_SCOPES', JIRA_SCOPES)
os.environ.setdefault('FRONTEND_URL', FRONTEND_URL)

os.environ.setdefault('BAMBOOHR_CLIENT_ID', BAMBOOHR_CLIENT_ID)
os.environ.setdefault('BAMBOOHR_CLIENT_SECRET', BAMBOOHR_CLIENT_SECRET)
os.environ.setdefault('BAMBOOHR_REDIRECT_URI', BAMBOOHR_REDIRECT_URI)
os.environ.setdefault('BAMBOOHR_SCOPES', BAMBOOHR_SCOPES)
os.environ.setdefault('USE_LOCAL_DEVELOPMENT', str(USE_LOCAL_DEVELOPMENT))
os.environ.setdefault('BAMBOOHR_FLASK_SERVER_URL', BAMBOOHR_FLASK_SERVER_URL)
os.environ.setdefault('SKIP_OAUTH_STATE_VERIFICATION', SKIP_OAUTH_STATE_VERIFICATION)

os.environ.setdefault('GOOGLE_CLIENT_ID', GOOGLE_CLIENT_ID)
os.environ.setdefault('GOOGLE_CLIENT_SECRET', GOOGLE_CLIENT_SECRET)
os.environ.setdefault('GOOGLE_REDIRECT_URI', GOOGLE_REDIRECT_URI)
os.environ.setdefault('GOOGLE_SCOPES', GOOGLE_SCOPES)

# Redis configuration for Phase 2 AI caching
os.environ.setdefault('REDIS_URL', REDIS_URL)

# Ollama configuration (fallback)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://13.126.18.17:11434')
# Default timeout (seconds) for Ollama HTTP requests
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '600'))
# Default Ollama model to use (must exist on server per /api/tags)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:3b')
# AI consistency settings for reproducible results
OLLAMA_TEMPERATURE = float(os.environ.get('OLLAMA_TEMPERATURE', '0.1'))  # Low temperature for consistency
OLLAMA_SEED = int(os.environ.get('OLLAMA_SEED', '42'))  # Fixed seed for reproducibility

# =========================================================================
# SUPPRESS DJANGO RUNSERVER WARNINGS - Monkey patch sys.stderr
# =========================================================================
class _StderrFilter:
    """Filter out Django development server warnings"""
    def __init__(self, original):
        self._original = original
        
    def write(self, message):
        # Skip warning messages
        if any(phrase in message for phrase in [
            'WARNING: This is a development server',
            'Do not use it in a production setting',
            'For more information on production servers see',
            'https://docs.djangoproject.com/en'
        ]):
            return
        return self._original.write(message)
    
    def flush(self):
        return self._original.flush()
    
    def __getattr__(self, name):
        return getattr(self._original, name)

# Apply the filter to sys.stderr
if 'runserver' in sys.argv:
    sys.stderr = _StderrFilter(sys.stderr)