# Generated by Django 4.2.7 on 2025-09-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('rfp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rfp_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rfp_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rfp_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('TECHNOLOGY', 'Technology'), ('CONSULTING', 'Consulting')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('evaluation_period_end', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('SUBMISSION_OPEN', 'Submission Open'), ('EVALUATION', 'Evaluation'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('primary_reviewer_id', models.IntegerField(blank=True, null=True)),
                ('executive_reviewer_id', models.IntegerField(blank=True, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('auto_publish', models.BooleanField(default=False)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_workflow_id', models.BigIntegerField(blank=True, null=True)),
                ('evaluation_method', models.CharField(choices=[('lowest_price', 'Lowest Price'), ('best_value', 'Best Value'), ('weighted_scoring', 'Weighted Scoring')], default='weighted_scoring', max_length=20)),
                ('criticality_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('geographical_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('compliance_requirements', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('final_evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('award_decision_date', models.DateTimeField(blank=True, null=True)),
                ('award_justification', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rfps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rfps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPEvaluationCriteria',
            fields=[
                ('criteria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=255)),
                ('criteria_description', models.TextField()),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluation_type', models.CharField(choices=[('scoring', 'Scoring'), ('binary', 'Binary'), ('narrative', 'Narrative')], default='scoring', max_length=10)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('veto_enabled', models.BooleanField(default=False)),
                ('veto_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_word_count', models.IntegerField(blank=True, null=True)),
                ('expected_boolean_answer', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='rfp.rfp')),
            ],
            options={
                'db_table': 'rfp_evaluation_criteria',
                'ordering': ['display_order', 'criteria_id'],
                'indexes': [models.Index(fields=['rfp'], name='rfp_evaluat_rfp_id_237e5a_idx'), models.Index(fields=['is_mandatory'], name='rfp_evaluat_is_mand_3b5e95_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rfp',
            index=models.Index(fields=['rfp_number'], name='rfps_rfp_num_f94bda_idx'),
        ),
        migrations.AddIndex(
            model_name='rfp',
            index=models.Index(fields=['status'], name='rfps_status_e7f824_idx'),
        ),
        migrations.AddIndex(
            model_name='rfp',
            index=models.Index(fields=['created_by'], name='rfps_created_bd06c5_idx'),
        ),
    ]
