# Generated by Django 4.2.7 on 2025-09-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('is_active', models.CharField(max_length=45)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=1045, null=True)),
                ('consent_accepted', models.CharField(blank=True, max_length=1, null=True)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='RFPApprovalWorkflow',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('reviewer', 'Reviewer'), ('executive', 'Executive')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('sequence_order', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='rfp.customuser')),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='rfp.rfp')),
            ],
            options={
                'db_table': 'rfp_approval_workflow',
                'ordering': ['sequence_order', 'approval_id'],
                'indexes': [models.Index(fields=['rfp'], name='rfp_approva_rfp_id_0d3fd1_idx'), models.Index(fields=['approver'], name='rfp_approva_approve_8c4b72_idx'), models.Index(fields=['status'], name='rfp_approva_status_bf3fc5_idx')],
            },
        ),
    ]
