# Generated by Django 4.2.7 on 2025-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0002_customuser_rfpapprovalworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='rfp_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
