# Generated by Django 4.2.7 on 2025-09-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0002_vendor_models'),
        ('rfp', '0005_rfpunmatchedvendor_rfpvendorselection_vendor_and_more'),
    ]

    operations = [
    ]
