# Generated by Django 4.2.7 on 2025-09-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0009_fix_invitation_id_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFPApprovalWorkflow',
        ),
    ]
