# Generated by Django 4.2.7 on 2025-09-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0010_delete_rfpapprovalworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvitation',
            fields=[
                ('invitation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invited_date', models.DateTimeField(auto_now_add=True)),
                ('invitation_status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('ACKNOWLEDGED', 'Acknowledged'), ('DECLINED', 'Declined'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('invitation_url', models.CharField(blank=True, max_length=500, null=True)),
                ('acknowledgment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('submission_url', models.CharField(blank=True, max_length=500, null=True)),
                ('unique_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_matched_vendor', models.BooleanField(default=True)),
                ('submission_source', models.CharField(choices=[('invited', 'Invited'), ('open', 'Open')], default='invited', max_length=10)),
                ('utm_parameters', models.JSONField(blank=True, null=True)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rfp.rfp')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rfp.vendor')),
            ],
            options={
                'db_table': 'rfp_vendor_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
