# Generated by Django 4.2.7 on 2025-09-25 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfp', '0011_vendorinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPResponse',
            fields=[
                ('response_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('invitation_id', models.BigIntegerField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('response_documents', models.JSONField(blank=True, null=True)),
                ('document_urls', models.JSONField(blank=True, null=True)),
                ('proposed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commercial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weighted_final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evaluation_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_EVALUATION', 'Under Evaluation'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('AWARDED', 'Awarded')], default='SUBMITTED', max_length=20)),
                ('auto_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submission_source', models.CharField(choices=[('invited', 'Invited'), ('open', 'Open')], default='invited', max_length=10)),
                ('external_submission_data', models.JSONField(blank=True, null=True)),
                ('draft_data', models.JSONField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
                ('evaluation_comments', models.TextField(blank=True, null=True)),
                ('technical_proposal', models.TextField(blank=True, null=True)),
                ('commercial_proposal', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfp.rfp')),
            ],
            options={
                'db_table': 'rfp_responses',
                'ordering': ['-submission_date'],
            },
        ),
    ]
