# Generated by Django 4.2.7 on 2025-09-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0012_rfpresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFPResponse',
        ),
    ]
