# Generated by Django 4.2.7 on 2025-09-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0013_delete_rfpresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPResponse',
            fields=[
                ('response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('proposal_data', models.JSONField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfp.vendorinvitation')),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfp.rfp')),
            ],
            options={
                'db_table': 'rfp_responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation'], name='rfp_respons_invitat_195fed_idx'), models.Index(fields=['rfp'], name='rfp_respons_rfp_id_99ab18_idx'), models.Index(fields=['contact_email'], name='rfp_respons_contact_b48968_idx'), models.Index(fields=['submission_status'], name='rfp_respons_submiss_571ee9_idx')],
            },
        ),
    ]
