# Generated by Django 4.2.7 on 2025-09-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0014_rfpresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpresponse',
            name='auto_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='commercial_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='completion_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='document_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='draft_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='evaluated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='evaluation_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='evaluation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='evaluation_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_EVALUATION', 'Under Evaluation'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('AWARDED', 'Awarded')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='external_submission_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='invitation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='proposed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='response_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='submission_source',
            field=models.CharField(choices=[('invited', 'Invited'), ('open', 'Open')], default='invited', max_length=10),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='technical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='vendor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpresponse',
            name='weighted_final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
