# Generated by Django 4.2.7 on 2025-09-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0017_remove_duplicate_invitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvitation',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rfp.vendor'),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='invited_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='acknowledged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='declined_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='acknowledgment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='is_matched_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='utm_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvitation',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
