# Generated by Django 4.2.7 on 2025-09-26 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0018_add_missing_vendor_invitation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvitation',
            name='invited_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='S3Files',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 's3_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id'], name='s3_files_user_id_9fdee7_idx'), models.Index(fields=['file_type'], name='s3_files_file_ty_94fbef_idx'), models.Index(fields=['uploaded_at'], name='s3_files_uploade_646351_idx')],
            },
        ),
    ]
