# Generated by Django 4.2.7 on 2025-09-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0003_alter_rfp_rfp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='rfp_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('TECHNOLOGY', 'Technology'), ('CONSULTING', 'Consulting'), ('SOFTWARE', 'Software')], max_length=10),
        ),
    ]
