# Generated by Django 4.2.7 on 2025-09-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0004_alter_rfp_rfp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPUnmatchedVendor',
            fields=[
                ('unmatched_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invitation_id', models.BigIntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_email', models.EmailField(max_length=255)),
                ('vendor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('submission_data', models.JSONField(blank=True, null=True)),
                ('matched_vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('matching_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('pending_review', 'Pending Review'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rfp_unmatched_vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPVendorSelection',
            fields=[
                ('selection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selection_method', models.CharField(choices=[('existing', 'Existing Vendor'), ('manual', 'Manual Entry'), ('bulk_upload', 'Bulk Upload')], max_length=20)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('selection_notes', models.TextField(blank=True, null=True)),
                ('selected_by', models.IntegerField(default=1)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rfp_vendor_selections',
                'ordering': ['-selected_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('duns_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('industry_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('headquarters_country', models.CharField(blank=True, max_length=100, null=True)),
                ('headquarters_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('lifecycle_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('onboarding_date', models.DateField(blank=True, null=True)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('is_critical_vendor', models.BooleanField(default=False)),
                ('has_data_access', models.BooleanField(default=False)),
                ('has_system_access', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rfpapprovalworkflow',
            name='rfp_approva_approve_8c4b72_idx',
        ),
        migrations.RenameIndex(
            model_name='rfp',
            new_name='rfps_created_382c70_idx',
            old_name='rfps_created_bd06c5_idx',
        ),
        migrations.RemoveField(
            model_name='rfpapprovalworkflow',
            name='approver',
        ),
        migrations.AddField(
            model_name='rfpapprovalworkflow',
            name='approver_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_id',
            field=models.IntegerField(blank=True, db_column='DepartmentId', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_column='FirstName', max_length=45),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.CharField(db_column='IsActive', max_length=45),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_column='LastName', max_length=45),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(db_column='Password', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(db_column='UserId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_column='UserName', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='approved_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='rfp_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('TECHNOLOGY', 'Technology'), ('CONSULTING', 'Consulting'), ('SOFTWARE', 'Software'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rfpevaluationcriteria',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='rfpapprovalworkflow',
            index=models.Index(fields=['approver_id'], name='rfp_approva_approve_8c4b72_idx'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfp.vendorcategory'),
        ),
        migrations.AddField(
            model_name='rfpvendorselection',
            name='rfp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_selections', to='rfp.rfp'),
        ),
        migrations.AddField(
            model_name='rfpvendorselection',
            name='unmatched_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rfp.rfpunmatchedvendor'),
        ),
        migrations.AddField(
            model_name='rfpvendorselection',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rfp.vendor'),
        ),
        migrations.AddIndex(
            model_name='rfpunmatchedvendor',
            index=models.Index(fields=['vendor_email'], name='rfp_unmatch_vendor__3c078f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfpunmatchedvendor',
            index=models.Index(fields=['matching_status'], name='rfp_unmatch_matchin_83dc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfpunmatchedvendor',
            index=models.Index(fields=['invitation_id'], name='rfp_unmatch_invitat_5ddd01_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_code'], name='vendors_vendor__656704_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company_name'], name='vendors_company_87e67f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_status_079e23_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['risk_level'], name='vendors_risk_le_f2d732_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_category'], name='vendors_vendor__3b9121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfpvendorselection',
            unique_together={('rfp', 'vendor')},
        ),
    ]
