# Generated by Django 4.2.7 on 2025-09-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0006_merge_20250920_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorCategory',
        ),
        migrations.RenameIndex(
            model_name='rfpunmatchedvendor',
            new_name='rfp_unmatch_vendor__3c078f_idx',
            old_name='rfp_unmatch_vendor__d9f20f_idx',
        ),
        migrations.RenameIndex(
            model_name='rfpunmatchedvendor',
            new_name='rfp_unmatch_matchin_83dc6f_idx',
            old_name='rfp_unmatch_matchin_4c9a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='rfpvendorselection',
            new_name='rfp_vendor__rfp_id_1d18d7_idx',
            old_name='rfp_vendor__rfp_id_c1c8f4_idx',
        ),
        migrations.RenameIndex(
            model_name='rfpvendorselection',
            new_name='rfp_vendor__vendor__fba805_idx',
            old_name='rfp_vendor__vendor__6a4a4e_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_vendor__656704_idx',
            old_name='vendors_vendor__1e7ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_company_87e67f_idx',
            old_name='vendors_company_2c4f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_status_079e23_idx',
            old_name='vendors_status_e9c337_idx',
        ),
        migrations.AlterField(
            model_name='rfp',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('SUBMISSION_OPEN', 'Submission Open'), ('EVALUATION', 'Evaluation'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfpapprovalworkflow',
            name='approver_id',
            field=models.IntegerField(),
        ),
    ]
