# Generated by Django 4.2.7 on 2025-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0007_add_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='approval_workflow_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
