# Generated by Django 4.2.7 on 2025-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0015_update_rfp_response_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('export', 'Export')], max_length=20)),
                ('user_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=500)),
                ('original_name', models.CharField(blank=True, max_length=500, null=True)),
                ('stored_name', models.CharField(blank=True, max_length=500, null=True)),
                ('s3_url', models.TextField(blank=True, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('export_format', models.CharField(blank=True, max_length=20, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('platform', models.CharField(default='S3_Microservice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_storage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='file_storag_user_id_963320_idx'), models.Index(fields=['operation_type'], name='file_storag_operati_4965d1_idx'), models.Index(fields=['status'], name='file_storag_status_f9eb42_idx'), models.Index(fields=['created_at'], name='file_storag_created_391493_idx'), models.Index(fields=['file_type'], name='file_storag_file_ty_45e974_idx')],
            },
        ),
    ]
