# Generated by Django 4.2.7 on 2025-09-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0016_filestorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfpresponse',
            name='invitation_id',
        ),
    ]
