-- =====================================================
-- SQL Script to Create Procurement Type Tables
-- RFI, RPQ, Direct, Auction, and Emergency
-- =====================================================

-- =====================================================
-- 1. RFI (Request for Information) Table
-- =====================================================
CREATE TABLE IF NOT EXISTS `rfis` (
  `rfi_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `rfi_number` VARCHAR(50) UNIQUE NULL,
  `rfi_title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `rfi_type` TEXT NOT NULL,
  `category` VARCHAR(100) NULL,
  `estimated_value` DECIMAL(15, 2) NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `budget_range_min` DECIMAL(15, 2) NULL,
  `budget_range_max` DECIMAL(15, 2) NULL,
  `issue_date` DATE NULL,
  `submission_deadline` DATETIME NULL,
  `evaluation_period_end` DATE NULL,
  `award_date` DATE NULL,
  `status` VARCHAR(20) DEFAULT 'DRAFT',
  `created_by` INT NOT NULL,
  `approved_by` INT NULL,
  `primary_reviewer_id` INT NULL,
  `executive_reviewer_id` INT NULL,
  `version_number` INT DEFAULT 1,
  `auto_approve` BOOLEAN DEFAULT FALSE,
  `allow_late_submissions` BOOLEAN DEFAULT FALSE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approval_workflow_id` VARCHAR(50) NULL,
  `evaluation_method` VARCHAR(20) DEFAULT 'weighted_scoring',
  `criticality_level` VARCHAR(10) DEFAULT 'medium',
  `geographical_scope` VARCHAR(255) NULL,
  `compliance_requirements` JSON NULL,
  `custom_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  `final_evaluation_score` DECIMAL(5, 2) NULL,
  `award_decision_date` DATETIME NULL,
  `award_justification` TEXT NULL,
  `documents` JSON NULL,
  INDEX `idx_rfi_number` (`rfi_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RFI Evaluation Criteria Table
CREATE TABLE IF NOT EXISTS `rfi_evaluation_criteria` (
  `criteria_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `rfi_id` BIGINT NOT NULL,
  `criteria_name` VARCHAR(255) NOT NULL,
  `criteria_description` TEXT NOT NULL,
  `weight_percentage` DECIMAL(5, 2) NOT NULL,
  `evaluation_type` VARCHAR(10) DEFAULT 'scoring',
  `min_score` DECIMAL(5, 2) NULL,
  `max_score` DECIMAL(5, 2) NULL,
  `median_score` DECIMAL(5, 2) NULL,
  `is_mandatory` BOOLEAN DEFAULT FALSE,
  `veto_enabled` BOOLEAN DEFAULT FALSE,
  `veto_threshold` DECIMAL(5, 2) NULL,
  `min_word_count` INT NULL,
  `expected_boolean_answer` VARCHAR(3) NULL,
  `display_order` INT DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_rfi` (`rfi_id`),
  INDEX `idx_is_mandatory` (`is_mandatory`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`rfi_id`) REFERENCES `rfis`(`rfi_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- 2. RPQ (Request for Quotation) Table
-- =====================================================
CREATE TABLE IF NOT EXISTS `rpqs` (
  `rpq_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `rpq_number` VARCHAR(50) UNIQUE NULL,
  `rpq_title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `rpq_type` TEXT NOT NULL,
  `category` VARCHAR(100) NULL,
  `estimated_value` DECIMAL(15, 2) NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `budget_range_min` DECIMAL(15, 2) NULL,
  `budget_range_max` DECIMAL(15, 2) NULL,
  `issue_date` DATE NULL,
  `submission_deadline` DATETIME NULL,
  `evaluation_period_end` DATE NULL,
  `award_date` DATE NULL,
  `status` VARCHAR(20) DEFAULT 'DRAFT',
  `created_by` INT NOT NULL,
  `approved_by` INT NULL,
  `primary_reviewer_id` INT NULL,
  `executive_reviewer_id` INT NULL,
  `version_number` INT DEFAULT 1,
  `auto_approve` BOOLEAN DEFAULT FALSE,
  `allow_late_submissions` BOOLEAN DEFAULT FALSE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approval_workflow_id` VARCHAR(50) NULL,
  `evaluation_method` VARCHAR(20) DEFAULT 'weighted_scoring',
  `criticality_level` VARCHAR(10) DEFAULT 'medium',
  `geographical_scope` VARCHAR(255) NULL,
  `compliance_requirements` JSON NULL,
  `custom_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  `final_evaluation_score` DECIMAL(5, 2) NULL,
  `award_decision_date` DATETIME NULL,
  `award_justification` TEXT NULL,
  `documents` JSON NULL,
  INDEX `idx_rpq_number` (`rpq_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RPQ Evaluation Criteria Table
CREATE TABLE IF NOT EXISTS `rpq_evaluation_criteria` (
  `criteria_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `rpq_id` BIGINT NOT NULL,
  `criteria_name` VARCHAR(255) NOT NULL,
  `criteria_description` TEXT NOT NULL,
  `weight_percentage` DECIMAL(5, 2) NOT NULL,
  `evaluation_type` VARCHAR(10) DEFAULT 'scoring',
  `min_score` DECIMAL(5, 2) NULL,
  `max_score` DECIMAL(5, 2) NULL,
  `median_score` DECIMAL(5, 2) NULL,
  `is_mandatory` BOOLEAN DEFAULT FALSE,
  `veto_enabled` BOOLEAN DEFAULT FALSE,
  `veto_threshold` DECIMAL(5, 2) NULL,
  `min_word_count` INT NULL,
  `expected_boolean_answer` VARCHAR(3) NULL,
  `display_order` INT DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_rpq` (`rpq_id`),
  INDEX `idx_is_mandatory` (`is_mandatory`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`rpq_id`) REFERENCES `rpqs`(`rpq_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- 3. Direct Procurement Table
-- =====================================================
CREATE TABLE IF NOT EXISTS `direct_procurements` (
  `direct_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `direct_number` VARCHAR(50) UNIQUE NULL,
  `direct_title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `direct_type` TEXT NOT NULL,
  `category` VARCHAR(100) NULL,
  `estimated_value` DECIMAL(15, 2) NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `budget_range_min` DECIMAL(15, 2) NULL,
  `budget_range_max` DECIMAL(15, 2) NULL,
  `issue_date` DATE NULL,
  `submission_deadline` DATETIME NULL,
  `evaluation_period_end` DATE NULL,
  `award_date` DATE NULL,
  `status` VARCHAR(20) DEFAULT 'DRAFT',
  `created_by` INT NOT NULL,
  `approved_by` INT NULL,
  `primary_reviewer_id` INT NULL,
  `executive_reviewer_id` INT NULL,
  `version_number` INT DEFAULT 1,
  `auto_approve` BOOLEAN DEFAULT FALSE,
  `allow_late_submissions` BOOLEAN DEFAULT FALSE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approval_workflow_id` VARCHAR(50) NULL,
  `evaluation_method` VARCHAR(20) DEFAULT 'weighted_scoring',
  `criticality_level` VARCHAR(10) DEFAULT 'medium',
  `geographical_scope` VARCHAR(255) NULL,
  `compliance_requirements` JSON NULL,
  `custom_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  `final_evaluation_score` DECIMAL(5, 2) NULL,
  `award_decision_date` DATETIME NULL,
  `award_justification` TEXT NULL,
  `documents` JSON NULL,
  `direct_justification` TEXT NULL COMMENT 'Justification for direct procurement',
  `vendor_id` BIGINT NULL COMMENT 'Pre-selected vendor for direct procurement',
  INDEX `idx_direct_number` (`direct_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_vendor` (`vendor_id`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Direct Procurement Evaluation Criteria Table
CREATE TABLE IF NOT EXISTS `direct_evaluation_criteria` (
  `criteria_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `direct_id` BIGINT NOT NULL,
  `criteria_name` VARCHAR(255) NOT NULL,
  `criteria_description` TEXT NOT NULL,
  `weight_percentage` DECIMAL(5, 2) NOT NULL,
  `evaluation_type` VARCHAR(10) DEFAULT 'scoring',
  `min_score` DECIMAL(5, 2) NULL,
  `max_score` DECIMAL(5, 2) NULL,
  `median_score` DECIMAL(5, 2) NULL,
  `is_mandatory` BOOLEAN DEFAULT FALSE,
  `veto_enabled` BOOLEAN DEFAULT FALSE,
  `veto_threshold` DECIMAL(5, 2) NULL,
  `min_word_count` INT NULL,
  `expected_boolean_answer` VARCHAR(3) NULL,
  `display_order` INT DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_direct` (`direct_id`),
  INDEX `idx_is_mandatory` (`is_mandatory`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`direct_id`) REFERENCES `direct_procurements`(`direct_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- 4. Auction Table
-- =====================================================
CREATE TABLE IF NOT EXISTS `auctions` (
  `auction_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `auction_number` VARCHAR(50) UNIQUE NULL,
  `auction_title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `auction_type` TEXT NOT NULL,
  `category` VARCHAR(100) NULL,
  `estimated_value` DECIMAL(15, 2) NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `budget_range_min` DECIMAL(15, 2) NULL,
  `budget_range_max` DECIMAL(15, 2) NULL,
  `issue_date` DATE NULL,
  `submission_deadline` DATETIME NULL,
  `evaluation_period_end` DATE NULL,
  `award_date` DATE NULL,
  `status` VARCHAR(20) DEFAULT 'DRAFT',
  `created_by` INT NOT NULL,
  `approved_by` INT NULL,
  `primary_reviewer_id` INT NULL,
  `executive_reviewer_id` INT NULL,
  `version_number` INT DEFAULT 1,
  `auto_approve` BOOLEAN DEFAULT FALSE,
  `allow_late_submissions` BOOLEAN DEFAULT FALSE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approval_workflow_id` VARCHAR(50) NULL,
  `evaluation_method` VARCHAR(20) DEFAULT 'weighted_scoring',
  `criticality_level` VARCHAR(10) DEFAULT 'medium',
  `geographical_scope` VARCHAR(255) NULL,
  `compliance_requirements` JSON NULL,
  `custom_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  `final_evaluation_score` DECIMAL(5, 2) NULL,
  `award_decision_date` DATETIME NULL,
  `award_justification` TEXT NULL,
  `documents` JSON NULL,
  `auction_start_time` DATETIME NULL COMMENT 'Auction start date and time',
  `auction_end_time` DATETIME NULL COMMENT 'Auction end date and time',
  `starting_bid` DECIMAL(15, 2) NULL COMMENT 'Starting bid amount',
  `reserve_price` DECIMAL(15, 2) NULL COMMENT 'Reserve price (minimum acceptable bid)',
  `bid_increment` DECIMAL(15, 2) NULL COMMENT 'Minimum bid increment',
  `auction_format` VARCHAR(50) NULL COMMENT 'e.g., English, Dutch, Sealed Bid',
  INDEX `idx_auction_number` (`auction_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_auction_times` (`auction_start_time`, `auction_end_time`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Auction Evaluation Criteria Table
CREATE TABLE IF NOT EXISTS `auction_evaluation_criteria` (
  `criteria_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `auction_id` BIGINT NOT NULL,
  `criteria_name` VARCHAR(255) NOT NULL,
  `criteria_description` TEXT NOT NULL,
  `weight_percentage` DECIMAL(5, 2) NOT NULL,
  `evaluation_type` VARCHAR(10) DEFAULT 'scoring',
  `min_score` DECIMAL(5, 2) NULL,
  `max_score` DECIMAL(5, 2) NULL,
  `median_score` DECIMAL(5, 2) NULL,
  `is_mandatory` BOOLEAN DEFAULT FALSE,
  `veto_enabled` BOOLEAN DEFAULT FALSE,
  `veto_threshold` DECIMAL(5, 2) NULL,
  `min_word_count` INT NULL,
  `expected_boolean_answer` VARCHAR(3) NULL,
  `display_order` INT DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_auction` (`auction_id`),
  INDEX `idx_is_mandatory` (`is_mandatory`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`auction_id`) REFERENCES `auctions`(`auction_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Auction Bids Table (for tracking bids)
CREATE TABLE IF NOT EXISTS `auction_bids` (
  `bid_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `auction_id` BIGINT NOT NULL,
  `vendor_id` BIGINT NULL,
  `bid_amount` DECIMAL(15, 2) NOT NULL,
  `bid_status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING, ACCEPTED, REJECTED, WITHDRAWN',
  `bid_submitted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `bid_accepted_at` DATETIME NULL,
  `bid_rejected_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  `created_by` INT NULL,
  `notes` TEXT NULL,
  INDEX `idx_auction` (`auction_id`),
  INDEX `idx_vendor` (`vendor_id`),
  INDEX `idx_bid_status` (`bid_status`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`auction_id`) REFERENCES `auctions`(`auction_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- 5. Emergency Procurement Table
-- =====================================================
CREATE TABLE IF NOT EXISTS `emergency_procurements` (
  `emergency_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `emergency_number` VARCHAR(50) UNIQUE NULL,
  `emergency_title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `emergency_type` TEXT NOT NULL,
  `category` VARCHAR(100) NULL,
  `estimated_value` DECIMAL(15, 2) NULL,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `budget_range_min` DECIMAL(15, 2) NULL,
  `budget_range_max` DECIMAL(15, 2) NULL,
  `issue_date` DATE NULL,
  `submission_deadline` DATETIME NULL,
  `evaluation_period_end` DATE NULL,
  `award_date` DATE NULL,
  `status` VARCHAR(20) DEFAULT 'DRAFT',
  `created_by` INT NOT NULL,
  `approved_by` INT NULL,
  `primary_reviewer_id` INT NULL,
  `executive_reviewer_id` INT NULL,
  `version_number` INT DEFAULT 1,
  `auto_approve` BOOLEAN DEFAULT FALSE,
  `allow_late_submissions` BOOLEAN DEFAULT FALSE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approval_workflow_id` VARCHAR(50) NULL,
  `evaluation_method` VARCHAR(20) DEFAULT 'weighted_scoring',
  `criticality_level` VARCHAR(10) DEFAULT 'medium',
  `geographical_scope` VARCHAR(255) NULL,
  `compliance_requirements` JSON NULL,
  `custom_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  `final_evaluation_score` DECIMAL(5, 2) NULL,
  `award_decision_date` DATETIME NULL,
  `award_justification` TEXT NULL,
  `documents` JSON NULL,
  `emergency_justification` TEXT NOT NULL COMMENT 'Justification for emergency procurement',
  `emergency_type_category` VARCHAR(100) NULL COMMENT 'e.g., Natural Disaster, System Failure, Security Breach',
  `urgency_level` VARCHAR(20) DEFAULT 'HIGH' COMMENT 'LOW, MEDIUM, HIGH, CRITICAL',
  `required_delivery_date` DATE NULL COMMENT 'Required delivery/completion date',
  `impact_description` TEXT NULL COMMENT 'Description of impact if not procured immediately',
  INDEX `idx_emergency_number` (`emergency_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_by` (`created_by`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_urgency_level` (`urgency_level`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Emergency Procurement Evaluation Criteria Table
CREATE TABLE IF NOT EXISTS `emergency_evaluation_criteria` (
  `criteria_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `emergency_id` BIGINT NOT NULL,
  `criteria_name` VARCHAR(255) NOT NULL,
  `criteria_description` TEXT NOT NULL,
  `weight_percentage` DECIMAL(5, 2) NOT NULL,
  `evaluation_type` VARCHAR(10) DEFAULT 'scoring',
  `min_score` DECIMAL(5, 2) NULL,
  `max_score` DECIMAL(5, 2) NULL,
  `median_score` DECIMAL(5, 2) NULL,
  `is_mandatory` BOOLEAN DEFAULT FALSE,
  `veto_enabled` BOOLEAN DEFAULT FALSE,
  `veto_threshold` DECIMAL(5, 2) NULL,
  `min_word_count` INT NULL,
  `expected_boolean_answer` VARCHAR(3) NULL,
  `display_order` INT DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_emergency` (`emergency_id`),
  INDEX `idx_is_mandatory` (`is_mandatory`),
  INDEX `idx_tenant` (`TenantId`),
  FOREIGN KEY (`emergency_id`) REFERENCES `emergency_procurements`(`emergency_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- Additional Supporting Tables
-- =====================================================

-- Procurement Type Custom Fields (shared across all types)
CREATE TABLE IF NOT EXISTS `procurement_type_custom_fields` (
  `procurement_type_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `procurement_type` VARCHAR(255) NOT NULL COMMENT 'RFI, RPQ, Direct, Auction, Emergency',
  `custom_fields` JSON NULL,
  `response_fields` JSON NULL,
  `data_inventory` JSON NULL,
  `retentionExpiry` DATE NULL,
  INDEX `idx_procurement_type` (`procurement_type`),
  INDEX `idx_tenant` (`TenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Procurement Responses (generic table for all procurement types)
CREATE TABLE IF NOT EXISTS `procurement_responses` (
  `response_id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `TenantId` INT NULL,
  `procurement_type` VARCHAR(50) NOT NULL COMMENT 'RFI, RPQ, Direct, Auction, Emergency',
  `procurement_id` BIGINT NOT NULL COMMENT 'ID from respective procurement table',
  `vendor_id` BIGINT NULL,
  `invitation_id` BIGINT NULL,
  `submission_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `response_documents` JSON NULL,
  `document_urls` JSON NULL,
  `proposed_value` DECIMAL(15, 2) NULL,
  `technical_score` DECIMAL(5, 2) NULL,
  `commercial_score` DECIMAL(5, 2) NULL,
  `overall_score` DECIMAL(5, 2) NULL,
  `weighted_final_score` DECIMAL(5, 2) NULL,
  `evaluation_status` VARCHAR(20) DEFAULT 'DRAFT',
  `auto_rejected` BOOLEAN DEFAULT FALSE,
  `rejection_reason` TEXT NULL,
  `submission_source` VARCHAR(10) DEFAULT 'invited',
  `external_submission_data` JSON NULL,
  `draft_data` JSON NULL,
  `completion_percentage` DECIMAL(5, 2) DEFAULT 0.0,
  `last_saved_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `submitted_by` VARCHAR(255) NULL,
  `evaluated_by` INT NULL,
  `evaluation_date` DATETIME NULL,
  `evaluation_comments` TEXT NULL,
  `org` VARCHAR(255) NULL,
  `vendor_name` VARCHAR(255) NULL,
  `contact_email` VARCHAR(255) NULL,
  `contact_phone` VARCHAR(50) NULL,
  `proposal_data` JSON NULL,
  `submission_status` VARCHAR(20) DEFAULT 'DRAFT',
  `submitted_at` DATETIME NULL,
  `ip_address` VARCHAR(45) NULL,
  `user_agent` TEXT NULL,
  INDEX `idx_procurement` (`procurement_type`, `procurement_id`),
  INDEX `idx_vendor` (`vendor_id`),
  INDEX `idx_evaluation_status` (`evaluation_status`),
  INDEX `idx_tenant` (`TenantId`),
  INDEX `idx_submission_date` (`submission_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- End of SQL Script
-- =====================================================
