# Generated by Django 4.2.7 on 2025-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRCLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('log_level', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'grc_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('module', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'quick_access_favorites',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
