# Generated by Django 5.2.6 on 2025-09-20 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['contract_name'],
            },
        ),
        migrations.CreateModel(
            name='SLAApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('sla_id', models.BigIntegerField(help_text='ID of the SLA being approved')),
                ('workflow_id', models.IntegerField(help_text='ID of the workflow')),
                ('workflow_name', models.CharField(help_text='Name of the workflow', max_length=255)),
                ('assigner_id', models.IntegerField(help_text='ID of the user who assigned the approval')),
                ('assigner_name', models.CharField(help_text='Name of the user who assigned the approval', max_length=255)),
                ('assignee_id', models.IntegerField(help_text='ID of the user assigned to approve')),
                ('assignee_name', models.CharField(help_text='Name of the user assigned to approve', max_length=255)),
                ('object_type', models.CharField(choices=[('SLA_CREATION', 'SLA Creation'), ('SLA_AMENDMENT', 'SLA Amendment'), ('SLA_RENEWAL', 'SLA Renewal'), ('SLA_TERMINATION', 'SLA Termination')], help_text='Type of SLA operation', max_length=20)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when approval was assigned')),
                ('due_date', models.DateTimeField(help_text='Due date for approval')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMMENTED', 'Commented'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ASSIGNED', help_text='Current status of the approval', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Priority level of the approval', max_length=10)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Overall approval status', max_length=20)),
                ('comment_text', models.TextField(blank=True, help_text='Comments on the approval', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Approval',
                'verbose_name_plural': 'SLA Approvals',
                'db_table': 'sla_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('metric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_unit', models.CharField(default='%', max_length=50)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('penalty', models.TextField(blank=True)),
                ('measurement_methodology', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SLA Metric',
                'verbose_name_plural': 'SLA Metrics',
                'db_table': 'sla_metrics',
                'ordering': ['metric_name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='SLADocument',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sla_name', models.CharField(max_length=255)),
                ('document_file', models.BinaryField()),
                ('file_type', models.CharField(max_length=50)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='sla_documents', to='slas.contract')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sla_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='sla_documents', to='slas.vendor')),
            ],
            options={
                'verbose_name': 'SLA Document',
                'verbose_name_plural': 'SLA Documents',
                'db_table': 'sla_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorSLA',
            fields=[
                ('sla_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sla_name', models.CharField(max_length=255)),
                ('sla_type', models.CharField(choices=[('AVAILABILITY', 'Availability'), ('RESPONSE_TIME', 'Response Time'), ('RESOLUTION_TIME', 'Resolution Time'), ('QUALITY', 'Quality'), ('CUSTOM', 'Custom')], max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('business_service_impacted', models.CharField(blank=True, max_length=255)),
                ('reporting_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('baseline_period', models.CharField(blank=True, max_length=100)),
                ('improvement_targets', models.JSONField(blank=True, default=dict)),
                ('penalty_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_methodology', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('force_majeure_clauses', models.TextField(blank=True)),
                ('compliance_framework', models.CharField(blank=True, max_length=255)),
                ('audit_requirements', models.TextField(blank=True)),
                ('document_versioning', models.CharField(blank=True, max_length=255)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_slas', to='slas.contract')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_slas', to='slas.vendor')),
            ],
            options={
                'verbose_name': 'Vendor SLA',
                'verbose_name_plural': 'Vendor SLAs',
                'db_table': 'vendor_slas',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SLAViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField()),
                ('violation_type', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('breach', 'Breach')], max_length=20)),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('expected_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('mitigation_actions', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('metric', models.ForeignKey(db_column='metric_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='slas.slametric')),
                ('sla', models.ForeignKey(db_column='sla_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='slas.vendorsla')),
            ],
            options={
                'verbose_name': 'SLA Violation',
                'verbose_name_plural': 'SLA Violations',
                'ordering': ['-violation_date'],
            },
        ),
        migrations.CreateModel(
            name='SLAReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('adhoc', 'Ad-hoc')], max_length=20)),
                ('overall_score', models.PositiveIntegerField(help_text='Overall SLA performance score (0-100)')),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('next_review_date', models.DateField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_reviews', to=settings.AUTH_USER_MODEL)),
                ('sla', models.ForeignKey(db_column='sla_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='slas.vendorsla')),
            ],
            options={
                'verbose_name': 'SLA Review',
                'verbose_name_plural': 'SLA Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddField(
            model_name='slametric',
            name='sla',
            field=models.ForeignKey(db_column='sla_id', on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='slas.vendorsla'),
        ),
        migrations.CreateModel(
            name='SLACompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('compliance_percentage', models.DecimalField(decimal_places=2, help_text='Compliance percentage', max_digits=5)),
                ('is_compliant', models.BooleanField()),
                ('breach_duration', models.DurationField(blank=True, null=True)),
                ('penalty_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metric', models.ForeignKey(db_column='metric_id', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='slas.slametric')),
                ('sla', models.ForeignKey(db_column='sla_id', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='slas.vendorsla')),
            ],
            options={
                'verbose_name': 'SLA Compliance',
                'verbose_name_plural': 'SLA Compliance Records',
                'ordering': ['-period_start'],
            },
        ),
    ]
