# Generated by Django 5.2.3 on 2025-08-25 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
                ('is_active_raw', models.CharField(blank=True, db_column='IsActive', max_length=45, null=True)),
                ('department_id', models.IntegerField(blank=True, db_column='DepartmentId', null=True)),
                ('session_token', models.CharField(blank=True, db_column='session_token', max_length=1045, null=True)),
                ('consent_accepted', models.CharField(blank=True, db_column='consent_accepted', max_length=1, null=True)),
                ('license_key', models.CharField(blank=True, db_column='license_key', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfaAuditLog',
            fields=[
                ('mfa_event_id', models.BigAutoField(db_column='MfaEventId', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('challenge_issued', 'challenge_issued'), ('challenge_ok', 'challenge_ok'), ('challenge_fail', 'challenge_fail')], db_column='EventType', max_length=32)),
                ('detail_json', models.JSONField(blank=True, db_column='DetailJson', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='IpAddress', max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, db_column='UserAgent', max_length=400, null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_audit_events', to='mfa_auth.user')),
            ],
            options={
                'db_table': 'mfa_audit_log',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_mfaal_user_time')],
            },
        ),
        migrations.CreateModel(
            name='MfaEmailChallenge',
            fields=[
                ('challenge_id', models.BigAutoField(db_column='ChallengeId', primary_key=True, serialize=False)),
                ('otp_hash', models.BinaryField(db_column='OtpHash', max_length=64)),
                ('expires_at', models.DateTimeField(db_column='ExpiresAt')),
                ('attempts', models.IntegerField(db_column='Attempts', default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('satisfied', 'satisfied'), ('expired', 'expired'), ('failed', 'failed')], db_column='Status', default='pending', max_length=16)),
                ('ip_address', models.CharField(blank=True, db_column='IpAddress', max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, db_column='UserAgent', max_length=400, null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, db_column='UsedAt', null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to='mfa_auth.user')),
            ],
            options={
                'db_table': 'mfa_email_challenges',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_mfaec_user_status'), models.Index(fields=['expires_at'], name='idx_mfaec_expires')],
            },
        ),
    ]
