export const mockContracts = [
  {
    id: 'CNT-2024-001',
    title: 'Cloud Infrastructure Services',
    vendor_name: 'Acme Cloud Ltd.',
    contract_number: 'AC-2024-001',
    value: 500000,
    currency: 'USD',
    status: 'Active',
    risk_level: 'Medium',
    start_date: '2024-04-01',
    end_date: '2027-03-31',
    type: 'SERVICE_CONTRACT',
    owner: 'John Smith',
    compliance_frameworks: ['SOC2', 'ISO27001']
  },
  {
    id: 'CNT-2024-002',
    title: 'Consulting Services',
    vendor_name: 'Global Consulting Inc.',
    contract_number: 'GC-2024-045',
    value: 250000,
    currency: 'USD',
    status: 'Draft',
    risk_level: 'Low',
    start_date: '2024-03-01',
    end_date: '2026-02-28',
    type: 'SOW',
    owner: 'Sarah Johnson',
    compliance_frameworks: ['GDPR']
  },
  {
    id: 'CNT-2024-003',
    title: 'Software License Agreement',
    vendor_name: 'TechSoft LLC',
    contract_number: 'TS-2024-112',
    value: 750000,
    currency: 'USD',
    status: 'Review',
    risk_level: 'High',
    start_date: '2024-02-01',
    end_date: '2027-01-31',
    type: 'MASTER_AGREEMENT',
    owner: 'Michael Chen',
    compliance_frameworks: ['SOC2', 'CCPA']
  },
  {
    id: 'CNT-2024-004',
    title: 'Hardware Maintenance',
    vendor_name: 'DataCorp Systems',
    contract_number: 'DC-2024-078',
    value: 120000,
    currency: 'USD',
    status: 'Active',
    risk_level: 'Low',
    start_date: '2024-01-15',
    end_date: '2025-01-14',
    type: 'MAINTENANCE',
    owner: 'Lisa Wang',
    compliance_frameworks: ['ISO27001']
  },
  {
    id: 'CNT-2024-005',
    title: 'Marketing Services',
    vendor_name: 'Creative Agency Plus',
    contract_number: 'CA-2024-023',
    value: 180000,
    currency: 'USD',
    status: 'Active',
    risk_level: 'Medium',
    start_date: '2024-03-15',
    end_date: '2025-03-14',
    type: 'SERVICE_CONTRACT',
    owner: 'David Brown',
    compliance_frameworks: ['GDPR']
  },
  {
    id: 'CNT-2024-006',
    title: 'Office Supplies',
    vendor_name: 'OfficeMax Solutions',
    contract_number: 'OM-2024-156',
    value: 45000,
    currency: 'USD',
    status: 'Expired',
    risk_level: 'Low',
    start_date: '2023-06-01',
    end_date: '2024-05-31',
    type: 'PURCHASE_ORDER',
    owner: 'Jennifer Lee',
    compliance_frameworks: []
  }
]

