# Generated by Django 4.2.7 on 2025-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflows',
            fields=[
                ('workflow_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(choices=[('MULTI_LEVEL', 'Multi Level'), ('MULTI_PERSON', 'Multi Person')], max_length=20)),
                ('description', models.TextField()),
                ('business_object_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStages',
            fields=[
                ('stage_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approval_id', models.CharField(max_length=50)),
                ('stage_order', models.IntegerField()),
                ('stage_name', models.CharField(max_length=255)),
                ('stage_description', models.TextField()),
                ('assigned_user_id', models.IntegerField()),
                ('assigned_user_name', models.CharField(max_length=255)),
                ('assigned_user_role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=20)),
                ('stage_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('extended_deadline', models.DateTimeField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_stages',
                'ordering': ['stage_order', 'stage_id'],
                'indexes': [models.Index(fields=['approval_id'], name='approval_st_approva_5d45d7_idx'), models.Index(fields=['assigned_user_id'], name='approval_st_assigne_a23093_idx'), models.Index(fields=['stage_status'], name='approval_st_stage_s_1f285a_idx'), models.Index(fields=['stage_order'], name='approval_st_stage_o_9a2d0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestVersions',
            fields=[
                ('version_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approval_id', models.CharField(max_length=50)),
                ('version_number', models.IntegerField()),
                ('version_label', models.CharField(max_length=100)),
                ('json_payload', models.JSONField()),
                ('changes_summary', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_by_role', models.CharField(max_length=100)),
                ('version_type', models.CharField(choices=[('INITIAL', 'Initial'), ('REVISION', 'Revision'), ('CONSOLIDATION', 'Consolidation'), ('FINAL', 'Final')], default='INITIAL', max_length=20)),
                ('parent_version_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_request_versions',
                'ordering': ['-version_number', '-created_at'],
                'indexes': [models.Index(fields=['approval_id'], name='approval_re_approva_c537aa_idx'), models.Index(fields=['version_number'], name='approval_re_version_aeeab3_idx'), models.Index(fields=['is_current'], name='approval_re_is_curr_977a60_idx'), models.Index(fields=['parent_version_id'], name='approval_re_parent__07679e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequests',
            fields=[
                ('approval_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=50)),
                ('request_title', models.CharField(max_length=255)),
                ('request_description', models.TextField()),
                ('requester_id', models.IntegerField()),
                ('requester_department', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('request_data', models.JSONField()),
                ('overall_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id'], name='approval_re_workflo_9665b2_idx'), models.Index(fields=['requester_id'], name='approval_re_request_55eccf_idx'), models.Index(fields=['overall_status'], name='approval_re_overall_bf11ea_idx'), models.Index(fields=['priority'], name='approval_re_priorit_98f2d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComments',
            fields=[
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approval_id', models.CharField(max_length=50)),
                ('stage_id', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_comment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_text', models.TextField()),
                ('comment_type', models.CharField(choices=[('GENERAL', 'General'), ('REJECTION_REASON', 'Rejection Reason'), ('CLARIFICATION', 'Clarification'), ('APPROVAL_NOTE', 'Approval Note')], default='GENERAL', max_length=20)),
                ('commented_by', models.IntegerField()),
                ('commented_by_name', models.CharField(max_length=255)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_id'], name='approval_co_approva_419839_idx'), models.Index(fields=['stage_id'], name='approval_co_stage_i_a6fa5b_idx'), models.Index(fields=['parent_comment_id'], name='approval_co_parent__b8a5a9_idx'), models.Index(fields=['commented_by'], name='approval_co_comment_119baa_idx')],
            },
        ),
    ]
