# Generated by Django 4.2.7 on 2025-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalcomments',
            name='approval_id',
            field=models.CharField(max_length=50),
        ),
    ]
