# Generated by Django 4.2.7 on 2025-09-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('audit_finding_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('metrics_id', models.IntegerField()),
                ('evidence', models.TextField()),
                ('user_id', models.IntegerField()),
                ('how_to_verify', models.TextField()),
                ('impact_recommendations', models.TextField()),
                ('details_of_finding', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('check_date', models.DateField()),
                ('questionnaire_responses', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'db_table': 'audit_findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('report_link', models.CharField(max_length=500)),
                ('sla_id', models.IntegerField()),
                ('metrics_id', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Report',
                'verbose_name_plural': 'Audit Reports',
                'db_table': 'audit_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('version_type', models.CharField(choices=[('A', 'Audit'), ('R', 'Review')], max_length=1)),
                ('version_number', models.IntegerField()),
                ('extended_information', models.JSONField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Version',
                'verbose_name_plural': 'Audit Versions',
                'db_table': 'audit_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticQuestionnaire',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes/No'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('scoring_weightings', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Static Questionnaire',
                'verbose_name_plural': 'Static Questionnaires',
                'db_table': 'static_questionnaires',
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True, null=True)),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('auditor_id', models.IntegerField(blank=True, null=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='created', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('reviewer_id', models.IntegerField(blank=True, null=True)),
                ('metric_id', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('audit_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External'), ('self', 'Self Assessment')], max_length=20, null=True)),
                ('evidence_comments', models.TextField(blank=True, null=True)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('reports_objective', models.TextField(blank=True, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla', models.ForeignKey(blank=True, db_column='sla_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='slas.vendorsla')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'db_table': 'audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
