# Generated by Django 4.2.7 on 2025-09-21 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('FrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkName', models.CharField(max_length=255)),
                ('CurrentVersion', models.FloatField()),
                ('FrameworkDescription', models.TextField()),
                ('EffectiveDate', models.DateField()),
                ('CreatedByName', models.CharField(max_length=255)),
                ('CreatedByDate', models.DateField()),
                ('Category', models.CharField(max_length=100)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('Identifier', models.CharField(blank=True, max_length=45, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(max_length=45)),
                ('ActiveInactive', models.CharField(max_length=45)),
                ('Reviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('InternalExternal', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'frameworks',
            },
        ),
        migrations.CreateModel(
            name='ComplianceMapping',
            fields=[
                ('mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sla_id', models.BigIntegerField()),
                ('framework_id', models.IntegerField()),
                ('compliance_status', models.CharField(default='Compliant', max_length=50)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_audited', models.DateField(blank=True, null=True)),
                ('next_audit_due', models.DateField(blank=True, null=True)),
                ('assigned_auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20)),
                ('compliance_version', models.CharField(max_length=50)),
                ('compliance_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_mapping',
                'unique_together': {('sla_id', 'framework_id')},
            },
        ),
    ]
