# Generated by Django 5.2.3 on 2025-09-16 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('amendment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_id', models.BigIntegerField(help_text='Contract ID')),
                ('amendment_number', models.CharField(help_text='Amendment number', max_length=50)),
                ('amendment_date', models.DateTimeField(help_text='Amendment date')),
                ('amendment_reason', models.TextField(help_text='Reason for amendment')),
                ('changes_summary', models.TextField(help_text='Summary of changes')),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Financial impact of amendment', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_by', models.IntegerField(blank=True, help_text='Approved by user ID', null=True)),
                ('effective_date', models.DateTimeField(help_text='Effective date of amendment')),
                ('attachment_path', models.CharField(blank=True, help_text='Path to amendment attachment', max_length=500, null=True)),
                ('amended_clause_ids', models.TextField(blank=True, help_text='Comma-separated list of amended clause IDs', null=True)),
                ('amended_term_ids', models.TextField(blank=True, help_text='Comma-separated list of amended term IDs', null=True)),
                ('affected_area', models.CharField(blank=True, choices=[('terms', 'Terms'), ('clauses', 'Clauses'), ('both', 'Both')], help_text='Area affected by the amendment', max_length=10, null=True)),
                ('workflow_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', help_text='Current workflow status of the amendment', max_length=15)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date when amendment was approved', null=True)),
                ('amendment_version', models.CharField(blank=True, help_text='Version of the amendment', max_length=20, null=True)),
                ('justification', models.TextField(blank=True, help_text='Detailed justification for the amendment', null=True)),
                ('supporting_documents', models.JSONField(blank=True, help_text='JSON array of supporting document paths', null=True)),
                ('initiated_by', models.IntegerField(blank=True, help_text='User ID who initiated the amendment', null=True)),
                ('initiated_date', models.DateTimeField(blank=True, help_text='Date when amendment was initiated', null=True)),
                ('amendment_notes', models.TextField(blank=True, help_text='Additional notes about the amendment', null=True)),
            ],
            options={
                'db_table': 'contract_amendments',
                'ordering': ['-amendment_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('renewal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_id', models.BigIntegerField(help_text='Reference to the original contract')),
                ('renewal_date', models.DateField(help_text='Date when renewal process was initiated')),
                ('notification_sent_date', models.DateField(blank=True, help_text='Date when the renewal notification was sent', null=True)),
                ('decision_due_date', models.DateField(blank=True, help_text='Date by which a decision must be made', null=True)),
                ('renewal_decision', models.CharField(choices=[('RENEW', 'Renew'), ('RENEGOTIATE', 'Renegotiate'), ('TERMINATE', 'Terminate'), ('PENDING', 'Pending')], default='PENDING', help_text='Renewal decision', max_length=20)),
                ('new_contract_id', models.BigIntegerField(blank=True, help_text='ID of the new contract created after renewal', null=True)),
                ('decided_by', models.IntegerField(blank=True, help_text='User who made the decision', null=True)),
                ('decision_date', models.DateField(blank=True, help_text='Date of decision', null=True)),
                ('comments', models.TextField(blank=True, help_text='Any comments regarding the renewal', null=True)),
                ('initiated_by', models.IntegerField(blank=True, help_text='User who initiated the renewal process', null=True)),
                ('initiated_date', models.DateTimeField(blank=True, help_text='Date when the renewal process was initiated outside the system', null=True)),
                ('renewal_reason', models.TextField(blank=True, help_text='Reason for the renewal', null=True)),
                ('renewal_documents', models.CharField(blank=True, help_text='Path or reference to renewal-related documents', max_length=500, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('under_review', 'Under Review'), ('decision_made', 'Decision Made')], default='initiated', help_text='Status of the renewal process', max_length=20)),
                ('renewed_contract_id', models.BigIntegerField(blank=True, help_text='Link to the original contract being renewed', null=True)),
            ],
            options={
                'verbose_name': 'Contract Renewal',
                'verbose_name_plural': 'Contract Renewals',
                'db_table': 'contract_renewals',
                'ordering': ['-renewal_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.BigIntegerField(help_text='Vendor ID')),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TECHNICAL', 'Technical'), ('BILLING', 'Billing'), ('LEGAL', 'Legal'), ('EMERGENCY', 'Emergency')], default='PRIMARY', help_text='Type of contact', max_length=20)),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job designation', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is primary contact')),
                ('is_active', models.BooleanField(default=True, help_text='Is active contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_contacts',
                'ordering': ['vendor_id', 'is_primary', 'contact_type', 'last_name', 'first_name'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contractclause',
            options={'managed': False, 'ordering': ['clause_type', 'clause_name']},
        ),
        migrations.AlterModelOptions(
            name='contractterm',
            options={'managed': False, 'ordering': ['term_category', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False, 'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='vendorcontract',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
