# Generated by Django 5.2.3 on 2025-09-17 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_update_version_number_to_decimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractamendment',
            options={'managed': True, 'ordering': ['-amendment_date']},
        ),
        migrations.AlterModelOptions(
            name='contractclause',
            options={'managed': True, 'ordering': ['clause_type', 'clause_name']},
        ),
        migrations.AlterModelOptions(
            name='contractterm',
            options={'managed': True, 'ordering': ['term_category', 'created_at']},
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.IntegerField(help_text='ID of the workflow this approval belongs to')),
                ('workflow_name', models.CharField(help_text='Name of the workflow', max_length=255)),
                ('assigner_id', models.IntegerField(help_text='ID of the user who assigned this approval')),
                ('assigner_name', models.CharField(help_text='Name of the user who assigned this approval', max_length=255)),
                ('assignee_id', models.IntegerField(help_text='ID of the user assigned to approve')),
                ('assignee_name', models.CharField(help_text='Name of the user assigned to approve', max_length=255)),
                ('object_type', models.CharField(choices=[('CONTRACT_CREATION', 'Contract Creation'), ('CONTRACT_AMENDMENT', 'Contract Amendment'), ('SUBCONTRACT_CREATION', 'Subcontract Creation'), ('CONTRACT_RENEWAL', 'Contract Renewal')], help_text='Type of object requiring approval', max_length=50)),
                ('object_id', models.IntegerField(help_text='ID of the contract requiring approval')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when approval was assigned')),
                ('due_date', models.DateTimeField(help_text='Date when approval is due')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMMENTED', 'Commented'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', help_text='Current status of the approval', max_length=20)),
                ('comment_text', models.TextField(blank=True, help_text='Comments from the assignee', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Approval',
                'verbose_name_plural': 'Contract Approvals',
                'db_table': 'contract_approvals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id'], name='contract_ap_workflo_b4dda2_idx'), models.Index(fields=['assignee_id'], name='contract_ap_assigne_047d79_idx'), models.Index(fields=['object_type', 'object_id'], name='contract_ap_object__88b76d_idx'), models.Index(fields=['status'], name='contract_ap_status_ba326a_idx'), models.Index(fields=['due_date'], name='contract_ap_due_dat_31f636_idx')],
            },
        ),
    ]
