# Generated by Django 4.2.7 on 2025-09-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_create_contract_approval'),
    ]

    operations = [
    ]
